cc_library(
    name = "Solution",
    srcs = [
        "Solution.cpp",
    ],
    hdrs = [
        "Solution.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//_common",
    ],
)
