#pragma once

#if defined(SOLUTION_01_PART1)
#include "01/part1/Solution.hpp"
#elif defined(SOLUTION_01_PART2)
#include "01/part2/Solution.hpp"
#elif defined(SOLUTION_02_PART1)
#include "02/part1/Solution.hpp"
#elif defined(SOLUTION_02_PART2)
#include "02/part2/Solution.hpp"
#elif defined(SOLUTION_03_PART1)
#include "03/part1/Solution.hpp"
#elif defined(SOLUTION_03_PART2)
#include "03/part2/Solution.hpp"
#elif defined(SOLUTION_04_PART1)
#include "04/part1/Solution.hpp"
#elif defined(SOLUTION_04_PART2)
#include "04/part2/Solution.hpp"
#elif defined(SOLUTION_05_PART1)
#include "05/part1/Solution.hpp"
#elif defined(SOLUTION_05_PART2)
#include "05/part2/Solution.hpp"
#elif defined(SOLUTION_06_PART1)
#include "06/part1/Solution.hpp"
#elif defined(SOLUTION_06_PART2)
#include "06/part2/Solution.hpp"
#elif defined(SOLUTION_07_PART1)
#include "07/part1/Solution.hpp"
#elif defined(SOLUTION_07_PART2)
#include "07/part2/Solution.hpp"
#elif defined(SOLUTION_08_PART1)
#include "08/part1/Solution.hpp"
#elif defined(SOLUTION_08_PART2)
#include "08/part2/Solution.hpp"
#elif defined(SOLUTION_09_PART1)
#include "09/part1/Solution.hpp"
#elif defined(SOLUTION_09_PART2)
#include "09/part2/Solution.hpp"
#else
#include "01/part1/Solution.hpp"
#endif