cc_library(
    name = "_common",
    srcs = [
        "Utils.cpp",
    ],
    hdrs = [
        "Debug.hpp",
        "ISolution.hpp",
        "Utils.h",
    ],
    visibility = ["//visibility:public"],
)
