cc_library(
    name = "_common",
    srcs = [
        "FileUtils.cpp",
    ],
    hdrs = [
        "Debug.hpp",
        "FileUtils.h",
        "ISolution.hpp",
    ],
    visibility = ["//visibility:public"],
)
