cc_library(
    name = "Solution01",
    srcs = [
        "part1/Solution01Part1.cpp",
        "part2/Solution01Part2.cpp",
    ],
    hdrs = [
        "part1/Solution01Part1.hpp",
        "part2/Solution01Part2.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//_common",
    ],
)
